import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createWorld } from "../../src/kernel.js";
import { activateWidgetVersion, defineWidgetVersion, defineWidgetVersionTransition } from "../../src/widgets.js";
import { worldGraphProjection, astNodesProjection } from "./world-graph.js";
import { processRunProjection, processViewProjection, renderProcessPage } from "./process-view.js";
import { renderWidgetPage } from "./widget-page.js";
import { requestWidgetVersionActivation, rollbackWidgetVersion } from "./widget-versions.js";

test("inspect plugin owns inspect bundle catalog, routes, and surfaces", async () => {
  const source = await readFile(new URL("./runtime.js", import.meta.url), "utf8");
  assert.equal(source.includes('bundleId = "bundle-inspect"'), true);
  assert.equal(source.includes('"worldGraph.read"'), true);
  assert.equal(source.includes('id: "surface:world"'), true);
});

test("inspect plugin owns world graph projections without a src compatibility facade", async () => {
  const pluginWorldGraph = await readFile(new URL("./world-graph.js", import.meta.url), "utf8");
  const runtimeSource = await readFile(new URL("./runtime.js", import.meta.url), "utf8");
  const graph = worldGraphProjection([]);

  assert.equal(typeof worldGraphProjection, "function");
  assert.equal(typeof astNodesProjection, "function");
  assert.deepEqual(graph.nodes.some(node => node.id === "genesis"), true);
  assert.equal(pluginWorldGraph.includes("export function worldGraphProjection"), true);
  assert.equal(pluginWorldGraph.includes("export function astNodesProjection"), true);
  assert.equal(runtimeSource.includes('from "./world-graph.js"'), true);
  await assert.rejects(readFile(new URL("../../src/world-graph.js", import.meta.url), "utf8"));
});

test("inspect plugin owns process view projections and page rendering without a src compatibility facade", async () => {
  const pluginProcessView = await readFile(new URL("./process-view.js", import.meta.url), "utf8");
  const runtimeSource = await readFile(new URL("./runtime.js", import.meta.url), "utf8");
  const model = processViewProjection({ witnesses: [], observations: [] }, {});

  assert.equal(typeof processViewProjection, "function");
  assert.equal(typeof processRunProjection, "function");
  assert.equal(typeof renderProcessPage, "function");
  assert.deepEqual(model.catalog, []);
  assert.match(renderProcessPage(model), /Process View/);
  assert.equal(pluginProcessView.includes("export function processViewProjection"), true);
  assert.equal(pluginProcessView.includes("export function processRunProjection"), true);
  assert.equal(pluginProcessView.includes("export function renderProcessPage"), true);
  assert.equal(runtimeSource.includes('from "./process-view.js"'), true);
  await assert.rejects(readFile(new URL("../../src/process-view.js", import.meta.url), "utf8"));
});

test("inspect plugin owns widget page rendering while src widgets stays model-focused", async () => {
  const pluginWidgetPage = await readFile(new URL("./widget-page.js", import.meta.url), "utf8");
  const surfaceCommandActionsSource = await readFile(new URL("./surface-command-actions.js", import.meta.url), "utf8");
  const surfaceCommandIdentityActionsSource = await readFile(new URL("./surface-command-identity-actions.js", import.meta.url), "utf8");
  const surfaceInspectorActionsSource = await readFile(new URL("./surface-inspector-actions.js", import.meta.url), "utf8");
  const surfaceInspectorFormActionsSource = await readFile(new URL("./surface-inspector-form-actions.js", import.meta.url), "utf8");
  const surfaceInspectorOverlayViewSource = await readFile(new URL("./surface-inspector-overlay-view.js", import.meta.url), "utf8");
  const surfaceInspectorVersionActionsSource = await readFile(new URL("./surface-inspector-version-actions.js", import.meta.url), "utf8");
  const worldCommandActionsSource = await readFile(new URL("./world-command-actions.js", import.meta.url), "utf8");
  const worldGraphActionsSource = await readFile(new URL("./world-graph-actions.js", import.meta.url), "utf8");
  const worldPostRenderSource = await readFile(new URL("./world-post-render.js", import.meta.url), "utf8");
  const worldShellViewSource = await readFile(new URL("./world-shell-view.js", import.meta.url), "utf8");
  const worldTutorialActionsSource = await readFile(new URL("./world-tutorial-actions.js", import.meta.url), "utf8");
  const surfaceKitSource = await readFile(new URL("./surface-kit-styles.js", import.meta.url), "utf8");
  const themeSource = await readFile(new URL("../eden/eden-page-theme.js", import.meta.url), "utf8");
  const runtimeSource = await readFile(new URL("./runtime.js", import.meta.url), "utf8");
  const srcWidgets = await readFile(new URL("../../src/widgets.js", import.meta.url), "utf8");

  assert.equal(typeof renderWidgetPage, "function");
  assert.equal(pluginWidgetPage.includes("export function renderWidgetPage"), true);
  assert.equal(pluginWidgetPage.includes("renderTutorialClient"), true);
  assert.equal(pluginWidgetPage.includes("resolveEdenPageTheme"), true);
  assert.equal(pluginWidgetPage.includes('from "./surface-command-actions.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./surface-command-identity-actions.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./surface-inspector-actions.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./surface-inspector-form-actions.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./surface-inspector-overlay-view.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./surface-inspector-version-actions.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./world-command-actions.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./world-graph-actions.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./world-post-render.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./world-shell-view.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./world-tutorial-actions.js"'), true);
  assert.equal(pluginWidgetPage.includes('from "./surface-kit-styles.js"'), true);
  assert.equal(pluginWidgetPage.includes("renderEdenPageThemeCssVars"), true);
  assert.equal(pluginWidgetPage.includes("const processTraceEnabled = config.traceProcessEvents !== false;"), true);
  assert.equal(pluginWidgetPage.includes("if (checkboxes === 'boolean')"), true);
  assert.equal(pluginWidgetPage.includes("setQueryParam"), true);
  assert.equal(pluginWidgetPage.includes("dispatchDomEvent"), true);
  assert.equal(pluginWidgetPage.includes("const syncInitialState ="), true);
  assert.equal(pluginWidgetPage.includes("const setHidden ="), true);
  assert.equal(pluginWidgetPage.includes("const setDisabled ="), true);
  assert.equal(pluginWidgetPage.includes("if (step.op === 'setHidden')"), true);
  assert.equal(pluginWidgetPage.includes("if (step.op === 'setDisabled')"), true);
  assert.equal(pluginWidgetPage.includes("bindSurfaceCommandActions({"), true);
  assert.equal(pluginWidgetPage.includes("bindSurfaceCommandIdentityActions({"), true);
  assert.equal(pluginWidgetPage.includes("bindSurfaceInspectorActions({"), true);
  assert.equal(pluginWidgetPage.includes("bindSurfaceInspectorFormActions({"), true);
  assert.equal(pluginWidgetPage.includes("ensureSurfaceInspectorOverlayRoot({ documentTarget: document });"), true);
  assert.equal(pluginWidgetPage.includes("renderSurfaceInspectorOverlayView({"), true);
  assert.equal(pluginWidgetPage.includes("bindSurfaceInspectorVersionActions({"), true);
  assert.equal(pluginWidgetPage.includes("bindWorldCommandActions({"), true);
  assert.equal(pluginWidgetPage.includes("bindWorldGraphActions({"), true);
  assert.equal(pluginWidgetPage.includes("queuePendingWorldSourceLoad({"), true);
  assert.equal(pluginWidgetPage.includes("runWorldPostRender({"), true);
  assert.equal(pluginWidgetPage.includes("renderWorldGraphShell({"), true);
  assert.equal(pluginWidgetPage.includes("bindWorldTutorialActions({"), true);
  assert.equal(pluginWidgetPage.includes("syncWorldCommandFocus({ root, state });"), false);
  assert.equal(pluginWidgetPage.includes("bindWorldCommandShortcuts({"), true);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-command-toggle]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-command-close]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-command-input]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-command-run]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-command-result-world]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-command-result-source]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-command-result-bootstrap]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-command-identity-form]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-toggle]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-close]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-clear]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-refresh]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-select]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-world]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-world-mode]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-open-process]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-activate]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-rollback]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-edit-form]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-proposal-form]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("overlay.querySelectorAll('[data-surface-inspector-version-proposal-form]').forEach(node => {"), false);
  assert.equal(pluginWidgetPage.includes("document.createElement('div');"), false);
  assert.equal(pluginWidgetPage.includes("overlay.innerHTML ="), true);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-command-toggle]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-command-close]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-command-input]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-command-run]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-mode]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-node-id], [data-world-select]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-kind]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-clear-kind]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-source-file]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-widget-activate]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-widget-rollback]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-open-process-program]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-jump-to-graph]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-close-source]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-primitive], [data-world-primitive-kind-only]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-close-primitive]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-focus-target]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-focus-scope-target]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-show-disabled]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-resume]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-next]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-back]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-restart-chapter]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-restart-step]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-enable-scope]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-enable-context]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-open-scope]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-disable]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-disable-context]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-exit]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("root.querySelectorAll('[data-world-tutorial-reset]').forEach(el => {"), false);
  assert.equal(pluginWidgetPage.includes("const canvas = root.querySelector('.world-graph-canvas');"), false);
  assert.equal(pluginWidgetPage.includes("updateWorldTutorialApi();"), false);
  assert.equal(pluginWidgetPage.includes("syncWorldCommandFocus({ root, state });"), false);
  assert.equal(pluginWidgetPage.includes("await safeRun('load');"), true);
  assert.equal(pluginWidgetPage.includes(".surface-card-grid"), false);
  assert.equal(pluginWidgetPage.includes("--page-bg:"), false);
  assert.equal(surfaceCommandActionsSource.includes("export function bindSurfaceCommandActions"), true);
  assert.equal(surfaceCommandActionsSource.includes("export function renderSurfaceCommandActionsFactory"), true);
  assert.equal(surfaceCommandIdentityActionsSource.includes("export function bindSurfaceCommandIdentityActions"), true);
  assert.equal(surfaceCommandIdentityActionsSource.includes("export async function submitSurfaceCommandIdentityForm"), true);
  assert.equal(surfaceCommandIdentityActionsSource.includes("export function renderSurfaceCommandIdentityActionsFactory"), true);
  assert.equal(surfaceInspectorActionsSource.includes("export function bindSurfaceInspectorActions"), true);
  assert.equal(surfaceInspectorActionsSource.includes("export function renderSurfaceInspectorActionsFactory"), true);
  assert.equal(surfaceInspectorFormActionsSource.includes("export function bindSurfaceInspectorFormActions"), true);
  assert.equal(surfaceInspectorFormActionsSource.includes("export async function submitSurfaceInspectorEditForm"), true);
  assert.equal(surfaceInspectorFormActionsSource.includes("export async function submitSurfaceInspectorProposalForm"), true);
  assert.equal(surfaceInspectorFormActionsSource.includes("export async function submitSurfaceInspectorVersionProposalForm"), true);
  assert.equal(surfaceInspectorFormActionsSource.includes("export function renderSurfaceInspectorFormActionsFactory"), true);
  assert.equal(surfaceInspectorOverlayViewSource.includes("export function ensureSurfaceInspectorOverlayRoot"), true);
  assert.equal(surfaceInspectorOverlayViewSource.includes("export function renderSurfaceInspectorOverlayView"), true);
  assert.equal(surfaceInspectorOverlayViewSource.includes("export function renderSurfaceInspectorOverlayViewFactory"), true);
  assert.equal(surfaceInspectorVersionActionsSource.includes("export function bindSurfaceInspectorVersionActions"), true);
  assert.equal(surfaceInspectorVersionActionsSource.includes("export async function runSurfaceInspectorActivateAction"), true);
  assert.equal(surfaceInspectorVersionActionsSource.includes("export async function runSurfaceInspectorRollbackAction"), true);
  assert.equal(surfaceInspectorVersionActionsSource.includes("export function renderSurfaceInspectorVersionActionsFactory"), true);
  assert.equal(worldCommandActionsSource.includes("export function bindWorldCommandActions"), true);
  assert.equal(worldCommandActionsSource.includes("export function syncWorldCommandFocus"), true);
  assert.equal(worldCommandActionsSource.includes("export function bindWorldCommandShortcuts"), true);
  assert.equal(worldCommandActionsSource.includes("export function renderWorldCommandActionsFactory"), true);
  assert.equal(worldGraphActionsSource.includes("export function bindWorldGraphActions"), true);
  assert.equal(worldGraphActionsSource.includes("export function renderWorldGraphActionsFactory"), true);
  assert.equal(worldPostRenderSource.includes("export function queuePendingWorldSourceLoad"), true);
  assert.equal(worldPostRenderSource.includes("export function syncWorldGraphViewport"), true);
  assert.equal(worldPostRenderSource.includes("export function syncWorldTutorialRenderState"), true);
  assert.equal(worldPostRenderSource.includes("export function runWorldPostRender"), true);
  assert.equal(worldPostRenderSource.includes("export function renderWorldPostRenderFactory"), true);
  assert.equal(worldShellViewSource.includes("export function renderWorldGraphShell"), true);
  assert.equal(worldShellViewSource.includes("export function renderWorldShellViewFactory"), true);
  assert.equal(worldTutorialActionsSource.includes("export function bindWorldTutorialActions"), true);
  assert.equal(worldTutorialActionsSource.includes("export function renderWorldTutorialActionsFactory"), true);
  assert.equal(surfaceKitSource.includes("export const SHARED_SURFACE_KIT_CSS"), true);
  assert.equal(surfaceKitSource.includes(".surface-card-grid"), true);
  assert.equal(surfaceKitSource.includes(".surface-link-chip"), true);
  assert.equal(themeSource.includes("export function renderEdenPageThemeCssVars"), true);
  assert.equal(runtimeSource.includes('from "./widget-page.js"'), true);
  assert.equal(srcWidgets.includes("function renderDocument"), false);
  assert.equal(srcWidgets.includes("renderTutorialClient"), false);
  assert.equal(srcWidgets.includes("resolveEdenPageTheme"), false);
  assert.equal(srcWidgets.includes("../plugins/inspect/widget-page.js"), false);
});

test("inspect plugin owns widget-version request and rollback workflows", async () => {
  const pluginWidgetVersions = await readFile(new URL("./widget-versions.js", import.meta.url), "utf8");
  const runtimeSource = await readFile(new URL("./runtime.js", import.meta.url), "utf8");
  const proposalsSource = await readFile(new URL("../proposals/proposal-executor.js", import.meta.url), "utf8");
  const srcWidgets = await readFile(new URL("../../src/widgets.js", import.meta.url), "utf8");
  const world = createWorld();

  defineWidgetVersion(world, { actor: "adam", soul: "banner", version: "banner_v1", kind: "Banner", props: { text: "One" } });
  defineWidgetVersion(world, { actor: "adam", soul: "banner", version: "banner_v2", kind: "Banner", props: { text: "Two" } });
  defineWidgetVersionTransition(world, { actor: "adam", soul: "banner", from: "banner_v1", to: "banner_v2", strategy: "migrate" });
  activateWidgetVersion(world, { actor: "adam", soul: "banner", version: "banner_v1" });

  const activated = requestWidgetVersionActivation(world, { actor: "adam", soul: "banner", version: "banner_v2" });
  const rolledBack = rollbackWidgetVersion(world, { actor: "adam", soul: "banner" });

  assert.equal(typeof requestWidgetVersionActivation, "function");
  assert.equal(typeof rollbackWidgetVersion, "function");
  assert.equal(activated.status, "migrated");
  assert.equal(rolledBack.status, "rolledBack");
  assert.equal(pluginWidgetVersions.includes("export function requestWidgetVersionActivation"), true);
  assert.equal(pluginWidgetVersions.includes("export function rollbackWidgetVersion"), true);
  assert.equal(runtimeSource.includes('from "./widget-versions.js"'), true);
  assert.equal(proposalsSource.includes('from "../inspect/widget-versions.js"'), true);
  assert.equal(srcWidgets.includes("export function requestWidgetVersionActivation"), false);
  assert.equal(srcWidgets.includes("export function rollbackWidgetVersion"), false);
  assert.equal(srcWidgets.includes("../plugins/inspect/widget-versions.js"), false);
});
