function freezeStrings(values = []) {
  return Object.freeze(values.map(value => String(value)));
}

function freezeCatalog({ authorableHandlers = [], pageHandlers = [], dispatchHandlers = [], handlerMetadata = {} }) {
  return Object.freeze({
    authorableHandlers: freezeStrings(authorableHandlers),
    pageHandlers: freezeStrings(pageHandlers),
    dispatchHandlers: freezeStrings(dispatchHandlers),
    handlerMetadata: Object.freeze(Object.fromEntries(
      Object.entries(handlerMetadata || {}).map(([handlerId, metadata]) => [String(handlerId), Object.freeze({ ...(metadata || {}) })])
    ))
  });
}

export const handlerCatalog = freezeCatalog({
  authorableHandlers: [
    "auth.oauth.start",
    "auth.oauth.callback",
    "auth.oauth.links.list",
    "auth.oauth.links.read",
    "runtimeConfig.read",
    "db.sql.inspect",
    "db.sql.migrate",
    "db.sql.query",
    "db.sql.command",
    "db.sql.transaction",
    "search.index.inspect",
    "search.index.build",
    "search.index.reindex",
    "search.index.query",
    "http.outbound.send",
    "http.outbound.list",
    "http.outbound.read",
    "webhook.inbound.receive",
    "webhook.inbound.list",
    "webhook.inbound.read",
    "backendSeams.read",
    "page.backendSeams",
    "fs.blob.list",
    "fs.blob.meta",
    "fs.blob.read",
    "fs.blob.write",
    "fs.blob.delete",
    "fs.stream.read",
    "fs.stream.write",
    "fs.stream.copy",
    "asset.ingest.retry",
    "asset.search.reindex",
    "asset.attachments.list",
    "asset.attach",
    "asset.detach"
  ],
  pageHandlers: ["page.backendSeams"],
  dispatchHandlers: [
    "auth.oauth.start",
    "auth.oauth.callback",
    "auth.oauth.links.list",
    "auth.oauth.links.read",
    "webhook.inbound.receive",
    "webhook.inbound.list",
    "webhook.inbound.read",
    "db.sql.inspect",
    "db.sql.migrate",
    "db.sql.query",
    "db.sql.command",
    "db.sql.transaction",
    "search.index.inspect",
    "search.index.build",
    "search.index.reindex",
    "search.index.query",
    "runtimeConfig.read",
    "http.outbound.send",
    "http.outbound.list",
    "http.outbound.read",
    "jobs.queue.enqueue",
    "jobs.queue.list",
    "jobs.queue.read",
    "notify.email.enqueue",
    "notify.sms.enqueue",
    "notifications.list",
    "notifications.read",
    "page.backendSeams",
    "fs.blob.list",
    "fs.blob.meta",
    "fs.blob.read",
    "fs.blob.write",
    "fs.blob.delete",
    "fs.stream.read",
    "fs.stream.write",
    "fs.stream.copy",
    "backendSeams.read",
    "asset.upload",
    "asset.ingest.retry",
    "asset.search.reindex",
    "asset.content.read",
    "asset.text.read",
    "asset.thumbnail.read",
    "asset.attachments.list",
    "asset.attach",
    "asset.detach"
  ]
});
