import assert from "node:assert/strict";
import test from "node:test";
import { renderBootstrapPage } from "../plugins/bootstrap/bootstrap-shell.js";

test("bootstrap shell renders the desktop ownership card and explicit desktop actions", () => {
  const html = renderBootstrapPage();

  assert.match(html, /<h2[^>]*>Local World Ownership<\/h2>/);
  assert.match(html, /id="desktop-summary"/);
  assert.match(html, /id="desktop-open-world"/);
  assert.match(html, /id="desktop-create-world"/);
  assert.match(html, /id="desktop-reveal-world"/);
  assert.match(html, /Desktop shell unavailable in this session\./);
  assert.match(html, /class="surface-page"/);
  assert.match(html, /class="surface-card surface-stack"/);
  assert.match(html, /class="surface-actions"/);
  assert.match(html, /data-action="openBootstrapAppHome"/);
  assert.match(html, /data-action="refreshBootstrapHost"/);
  assert.match(html, /data-action="openBootstrapDesktopWorld"/);
  assert.match(html, /data-action="createBootstrapDesktopWorld"/);
  assert.match(html, /data-action="revealBootstrapDesktopWorld"/);
  assert.match(html, /id="witness-bootstrap-top-cards-program"/);
  assert.match(html, /id="witness-bootstrap-top-cards-initial-state"/);
  assert.match(html, /id="witness-bootstrap-backend-authoring-controls-program"/);
  assert.match(html, /id="witness-bootstrap-backend-version-controls-program"/);
  assert.match(html, /id="witness-bootstrap-runtime-plugin-install-controls-program"/);
  assert.match(html, /id="witness-bootstrap-runtime-plugin-install-proposal-controls-program"/);
  assert.match(html, /id="witness-bootstrap-runtime-plugin-remove-proposal-controls-program"/);
  assert.match(html, /id="witness-bootstrap-mcp-server-controls-program"/);
  assert.match(html, /id="witness-bootstrap-mcp-server-proposal-controls-program"/);
  assert.match(html, /id="witness-bootstrap-mcp-tool-install-controls-program"/);
  assert.match(html, /id="witness-bootstrap-mcp-tool-install-proposal-controls-program"/);
  assert.match(html, /id="witness-bootstrap-mcp-tool-remove-proposal-controls-program"/);
  assert.match(html, /id="witness-bootstrap-proposal-create-controls-program"/);
  assert.match(html, /id="witness-bootstrap-proposal-review-controls-program"/);
  assert.match(html, /id="witness-bootstrap-context-binding-create-controls-program"/);
  assert.match(html, /id="witness-bootstrap-context-export-create-controls-program"/);
  assert.match(html, /id="witness-bootstrap-context-import-create-controls-program"/);
  assert.match(html, /id="witness-bootstrap-stewardship-create-controls-program"/);
  assert.match(html, /id="witness-bootstrap-starter-controls-program"/);
  assert.match(html, /id="witness-bootstrap-starter-controls-initial-state"/);
  assert.match(html, /id="witness-bootstrap-capability-create-controls-program"/);
  assert.match(html, /id="witness-bootstrap-capability-install-controls-program"/);
  assert.match(html, /const buildBootstrapCapabilityBaseSelectView =/);
  assert.match(html, /const applyBootstrapCapabilityBaseSelectView =/);
  assert.match(html, /const runBootstrapCapabilityControlsRender =/);
  assert.match(html, /const createBootstrapCapabilityControlsRuntime =/);
  assert.match(html, /const createBootstrapCapabilityControlsRuntimeFromBootstrap =/);
  assert.match(html, /id="witness-bootstrap-runtime-plugin-remove-controls-program"/);
  assert.match(html, /id="witness-bootstrap-mcp-tool-remove-controls-program"/);
  assert.match(html, /id="witness-bootstrap-capability-remove-controls-program"/);
  assert.match(html, /id="witness-bootstrap-context-binding-remove-controls-program"/);
  assert.match(html, /id="witness-bootstrap-context-export-remove-controls-program"/);
  assert.match(html, /id="witness-bootstrap-context-import-remove-controls-program"/);
  assert.match(html, /id="witness-bootstrap-stewardship-remove-controls-program"/);
  assert.match(html, /click:openBootstrapAppHome/);
  assert.match(html, /click:refreshBootstrapHost/);
  assert.match(html, /click:openBootstrapDesktopWorld/);
  assert.match(html, /click:createBootstrapDesktopWorld/);
  assert.match(html, /click:revealBootstrapDesktopWorld/);
  assert.match(html, /submit:bootstrap_identity_form/);
  assert.match(html, /witness:bootstrap-top-cards-submit/);
  assert.match(html, /data-action="clearBootstrapIdentityEdit"/);
  assert.match(html, /setQueryParam/);
  assert.match(html, /witness:host-refresh/);
  assert.match(html, /witness:bootstrap-host-action/);
  assert.match(html, /id="backend-program-form"/);
  assert.match(html, /id="backend-program-version-form"/);
  assert.match(html, /id="backend-step-form"/);
  assert.match(html, /submit:bootstrap_backend_program_form/);
  assert.match(html, /submit:bootstrap_backend_program_version_form/);
  assert.match(html, /submit:bootstrap_backend_step_form/);
  assert.match(html, /\/api\/backend-programs/);
  assert.match(html, /\/api\/backend-program-versions/);
  assert.match(html, /\/api\/backend-steps/);
  assert.match(html, /change:bootstrap_backend_program_version_soul_select/);
  assert.match(html, /change:bootstrap_backend_program_version_transition_from_select/);
  assert.match(html, /witness:bootstrap-backend-authoring-sync/);
  assert.match(html, /id="backend-program-activate-form"/);
  assert.match(html, /id="backend-program-rollback-form"/);
  assert.match(html, /submit:bootstrap_backend_activate_form/);
  assert.match(html, /submit:bootstrap_backend_rollback_form/);
  assert.match(html, /witness:bootstrap-backend-version-submit/);
  assert.match(html, /id="runtime-plugin-install-proposal-form"/);
  assert.match(html, /id="runtime-plugin-remove-proposal-form"/);
  assert.match(html, /id="runtime-plugin-install-form"/);
  assert.match(html, /submit:bootstrap_runtime_plugin_install_form/);
  assert.match(html, /witness:bootstrap-runtime-integration-direct-submit/);
  assert.match(html, /witness:bootstrap-runtime-integration-direct-sync/);
  assert.match(html, /id="mcp-server-proposal-form"/);
  assert.match(html, /id="mcp-server-form"/);
  assert.match(html, /submit:bootstrap_mcp_server_form/);
  assert.match(html, /id="mcp-tool-install-proposal-form"/);
  assert.match(html, /id="mcp-tool-install-form"/);
  assert.match(html, /submit:bootstrap_mcp_tool_install_form/);
  assert.match(html, /id="mcp-tool-remove-proposal-form"/);
  assert.match(html, /submit:bootstrap_runtime_plugin_install_proposal_form/);
  assert.match(html, /submit:bootstrap_runtime_plugin_remove_proposal_form/);
  assert.match(html, /submit:bootstrap_mcp_server_proposal_form/);
  assert.match(html, /submit:bootstrap_mcp_tool_install_proposal_form/);
  assert.match(html, /submit:bootstrap_mcp_tool_remove_proposal_form/);
  assert.match(html, /witness:bootstrap-proposal-adjacent-submit/);
  assert.match(html, /id="proposal-form"/);
  assert.match(html, /id="proposal-target-process"/);
  assert.match(html, /id="proposal-help"/);
  assert.match(html, /change:bootstrap_proposal_process_select/);
  assert.match(html, /change:bootstrap_proposal_kind_input/);
  assert.match(html, /change:bootstrap_proposal_target_input/);
  assert.match(html, /input:bootstrap_proposal_body_input/);
  assert.match(html, /witness:bootstrap-proposal-create-help-sync/);
  assert.match(html, /submit:bootstrap_proposal_create_form/);
  assert.match(html, /witness:bootstrap-proposal-submit/);
  assert.match(html, /id="proposal-approve-form"/);
  assert.match(html, /id="proposal-reject-form"/);
  assert.match(html, /change:bootstrap_proposal_approve_id_select/);
  assert.match(html, /witness:bootstrap-proposal-approve-help-sync/);
  assert.match(html, /submit:bootstrap_proposal_approve_form/);
  assert.match(html, /submit:bootstrap_proposal_reject_form/);
  assert.match(html, /witness:bootstrap-proposal-submit/);
  assert.match(html, /change:bootstrap_context_binding_create_context_select/);
  assert.match(html, /change:bootstrap_context_export_create_context_select/);
  assert.match(html, /change:bootstrap_context_import_create_source_context_select/);
  assert.match(html, /change:bootstrap_context_binding_remove_context_select/);
  assert.match(html, /change:bootstrap_context_export_remove_context_select/);
  assert.match(html, /change:bootstrap_context_import_remove_source_context_select/);
  assert.match(html, /witness:bootstrap-dependent-select-sync/);
  assert.match(html, /id="context-binding-form"/);
  assert.match(html, /submit:bootstrap_context_binding_create_form/);
  assert.match(html, /id="context-export-form"/);
  assert.match(html, /submit:bootstrap_context_export_create_form/);
  assert.match(html, /id="context-import-form"/);
  assert.match(html, /submit:bootstrap_context_import_create_form/);
  assert.match(html, /id="stewardship-form"/);
  assert.match(html, /submit:bootstrap_stewardship_create_form/);
  assert.match(html, /witness:bootstrap-scoped-submit/);
  assert.match(html, /clearForm/);
  assert.match(html, /id="runtime-plugin-remove-form"/);
  assert.match(html, /submit:bootstrap_runtime_plugin_remove_form/);
  assert.match(html, /witness:bootstrap-runtime-integration-direct-submit/);
  assert.match(html, /id="mcp-tool-remove-form"/);
  assert.match(html, /submit:bootstrap_mcp_tool_remove_form/);
  assert.match(html, /witness:bootstrap-runtime-integration-direct-submit/);
  assert.match(html, /id="capability-form"/);
  assert.match(html, /submit:bootstrap_capability_create_form/);
  assert.match(html, /schema":"capability\.define"/);
  assert.match(html, /witness:bootstrap-capability-submit/);
  assert.match(html, /id="capability-install-form"/);
  assert.match(html, /change:bootstrap_capability_install_capability_select/);
  assert.match(html, /change:bootstrap_capability_install_kind_select/);
  assert.match(html, /change:bootstrap_capability_install_target_select/);
  assert.match(html, /submit:bootstrap_capability_install_form/);
  assert.match(html, /schema":"capability\.install"/);
  assert.match(html, /id="capability-remove-form"/);
  assert.match(html, /change:bootstrap_capability_remove_capability_select/);
  assert.match(html, /change:bootstrap_capability_remove_kind_select/);
  assert.match(html, /change:bootstrap_capability_remove_target_select/);
  assert.match(html, /submit:bootstrap_capability_remove_form/);
  assert.match(html, /witness:bootstrap-capability-controls-sync/);
  assert.match(html, /witness:bootstrap-capability-submit/);
  assert.match(html, /id="context-binding-remove-form"/);
  assert.match(html, /submit:bootstrap_context_binding_remove_form/);
  assert.match(html, /id="context-export-remove-form"/);
  assert.match(html, /submit:bootstrap_context_export_remove_form/);
  assert.match(html, /id="context-import-remove-form"/);
  assert.match(html, /submit:bootstrap_context_import_remove_form/);
  assert.match(html, /id="stewardship-remove-form"/);
  assert.match(html, /submit:bootstrap_stewardship_remove_form/);
  assert.match(html, /witness:bootstrap-scoped-submit/);
  assert.match(html, /submit:bootstrap_session_form/);
  assert.match(html, /data-action="logoutBootstrapSession"/);
  assert.match(html, /click:logoutBootstrapSession/);
  assert.match(html, /witness:bootstrap-top-cards-submit/);
  assert.match(html, /submit:bootstrap_operator_backup_form/);
  assert.match(html, /submit:bootstrap_operator_export_form/);
  assert.match(html, /submit:bootstrap_operator_restore_form/);
  assert.match(html, /submit:bootstrap_operator_import_form/);
  assert.match(html, /checkboxes":"boolean"/);
  assert.match(html, /data-action="createBootstrapTodoStarter"/);
  assert.match(html, /repeat":\{"forEach":\{"from":"bootstrapStarterPlan\.requests","as":"item","serial":true\}\}/);
  assert.match(html, /id="create-todo-starter"/);
  assert.match(html, /id="starter-status"/);
});

test("bootstrap shell seeds projection-driven identity edit state for the authored top cards", () => {
  const html = renderBootstrapPage({
    requestUrl: "/_bootstrap?identity=identity.aaron",
    bootstrapState: {
      identities: [{
        id: "identity.aaron",
        actor: "aaron",
        label: "Aaron",
        username: "aaron",
        password: "aaron",
        homePerspective: "aaron:personal",
        homeContext: "aaron:home"
      }]
    }
  });

  assert.match(html, /witness-bootstrap-top-cards-initial-state/);
  assert.match(html, /"mode":"edit"/);
  assert.match(html, /"heading":"Edit Identity"/);
  assert.match(html, /"submitText":"Save Identity"/);
  assert.match(html, /"createNewHidden":false/);
  assert.match(html, /"idDisabled":true/);
  assert.match(html, /"actorDisabled":true/);
  assert.match(html, /"homeContext":"aaron:home"/);
});
