import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { bundleId, createHandlers, handlerCatalog, providers, routes } from "./runtime.js";
import { TODO_TUTORIAL_ID, normalizeTutorialProgress, tutorialDefinition } from "./tutorials.js";

test("tutorial plugin owns tutorial bundle routes and handlers", async () => {
  const manifest = JSON.parse(await readFile(new URL("./plugin.json", import.meta.url), "utf8"));

  assert.equal(manifest.id, "plugin.tutorial");
  assert.deepEqual(manifest.activatesBundles, ["bundle-tutorial"]);
  assert.equal(manifest.runtime.entry, "./runtime.js");
  assert.equal(bundleId, "bundle-tutorial");
  assert.deepEqual(handlerCatalog.dispatchHandlers, [
    "tutorial.progress.read",
    "tutorial.progress.write",
    "tutorial.progress.delete"
  ]);
  assert.equal(routes.some(route => route.handler === "tutorial.progress.read"), true);
  assert.equal(providers.some(provider => provider.kind === "runtimeBuiltinSeeds" && provider.valueTypes?.some(valueType => valueType.id === "widget.tutorialTarget")), true);
  assert.equal(typeof createHandlers({
    sendJson() {},
    readJson: async () => ({}),
    tutorialProgressFor: () => null,
    setTutorialProgress() {}
  })["tutorial.progress.read"], "function");
});

test("tutorial content and client helpers are plugin-owned without src compatibility facades", async () => {
  const tutorialSource = await readFile(new URL("./tutorials.js", import.meta.url), "utf8");
  const disabledScopesActionsSource = await readFile(new URL("./tutorial-disabled-scopes-actions.js", import.meta.url), "utf8");
  const appClientSource = await readFile(new URL("./tutorial-app-client.js", import.meta.url), "utf8");
  const clientAdapterSource = await readFile(new URL("./tutorial-client-adapter.js", import.meta.url), "utf8");
  const clientBootstrapSource = await readFile(new URL("./tutorial-client-bootstrap.js", import.meta.url), "utf8");
  const clientInteractionsSource = await readFile(new URL("./tutorial-client-interactions.js", import.meta.url), "utf8");
  const clientStateSource = await readFile(new URL("./tutorial-client-state.js", import.meta.url), "utf8");
  const disabledScopesViewSource = await readFile(new URL("./tutorial-disabled-scopes-view.js", import.meta.url), "utf8");
  const overlayDomSource = await readFile(new URL("./tutorial-overlay-dom.js", import.meta.url), "utf8");
  const overlayInteractionsSource = await readFile(new URL("./tutorial-overlay-interactions.js", import.meta.url), "utf8");
  const overlayViewSource = await readFile(new URL("./tutorial-overlay-view.js", import.meta.url), "utf8");
  const overlayActionsSource = await readFile(new URL("./tutorial-overlay-actions.js", import.meta.url), "utf8");
  const overlayDragSource = await readFile(new URL("./tutorial-overlay-drag.js", import.meta.url), "utf8");
  const progressRuntimeSource = await readFile(new URL("./tutorial-progress-runtime.js", import.meta.url), "utf8");
  const progressStateSource = await readFile(new URL("./tutorial-progress-state.js", import.meta.url), "utf8");
  const runtimeActionsSource = await readFile(new URL("./tutorial-runtime-actions.js", import.meta.url), "utf8");
  const runtimeUiSource = await readFile(new URL("./tutorial-runtime-ui.js", import.meta.url), "utf8");
  const tutorial = tutorialDefinition(TODO_TUTORIAL_ID);

  assert.equal(tutorial?.id, TODO_TUTORIAL_ID);
  assert.equal(normalizeTutorialProgress(tutorial, { stepId: tutorial.steps[0].id })?.stepId, tutorial.steps[0].id);
  assert.equal(tutorialSource.includes("export function tutorialDefinition"), true);
  assert.equal(tutorialSource.includes("todo-starter-blueprint.json"), true);
  assert.equal(appClientSource.includes("export function renderTutorialClient"), true);
  assert.equal(appClientSource.includes('./tutorial-disabled-scopes-actions.js'), true);
  assert.equal(appClientSource.includes('./tutorial-disabled-scopes-view.js'), true);
  assert.equal(appClientSource.includes('./tutorial-client-adapter.js'), true);
  assert.equal(appClientSource.includes('./tutorial-client-bootstrap.js'), true);
  assert.equal(appClientSource.includes('./tutorial-client-interactions.js'), true);
  assert.equal(appClientSource.includes('./tutorial-client-state.js'), true);
  assert.equal(appClientSource.includes('./tutorial-overlay-actions.js'), true);
  assert.equal(appClientSource.includes('./tutorial-overlay-drag.js'), true);
  assert.equal(appClientSource.includes('./tutorial-overlay-interactions.js'), true);
  assert.equal(appClientSource.includes('./tutorial-progress-runtime.js'), true);
  assert.equal(appClientSource.includes('./tutorial-progress-state.js'), true);
  assert.equal(appClientSource.includes('./tutorial-runtime-actions.js'), true);
  assert.equal(appClientSource.includes('./tutorial-overlay-dom.js'), true);
  assert.equal(appClientSource.includes('./tutorial-overlay-view.js'), true);
  assert.equal(appClientSource.includes("createTutorialOverlayDom({ document })"), true);
  assert.equal(appClientSource.includes("createTutorialOverlayDragState()"), true);
  assert.equal(appClientSource.includes("bindTutorialDisabledScopesActions({"), false);
  assert.equal(appClientSource.includes("bindTutorialOverlayActions({"), false);
  assert.equal(appClientSource.includes("bindTutorialOverlayDrag({"), false);
  assert.equal(appClientSource.includes("createTutorialProgressRuntime({"), true);
  assert.equal(appClientSource.includes("createTutorialProgressState({"), true);
  assert.equal(appClientSource.includes("createTutorialRuntimeActions({"), true);
  assert.equal(appClientSource.includes("createTutorialClientProgressAdapter({"), true);
  assert.equal(appClientSource.includes("bindTutorialClientRuntimeAdapters({"), true);
  assert.equal(appClientSource.includes("startTutorialClientRuntime({"), true);
  assert.equal(appClientSource.includes("createTutorialClientViewAdapter({"), true);
  assert.equal(appClientSource.includes("createTutorialClientInteractions({"), true);
  assert.equal(appClientSource.includes("createTutorialClientState({"), true);
  assert.equal(appClientSource.includes("tutorialClientApiRequest({"), false);
  assert.equal(appClientSource.includes("saveTutorialClientProgress({"), false);
  assert.equal(appClientSource.includes("renderTutorialClientDisabledScopes({"), false);
  assert.equal(appClientSource.includes("renderTutorialClientOverlay({"), false);
  assert.equal(appClientSource.includes("publishTutorialClientRuntimeSnapshot({"), false);
  assert.equal(appClientSource.includes("renderTutorialOverlayView({"), false);
  assert.equal(appClientSource.includes("publishTutorialRuntimeState({"), false);
  assert.equal(appClientSource.includes("focusTutorialOverlayTarget({"), false);
  assert.equal(appClientSource.includes("focusTutorialOverlayScopeTarget({"), false);
  assert.equal(appClientSource.includes("fillTutorialForm({"), false);
  assert.equal(appClientSource.includes("flashTutorialAutoClick({"), false);
  assert.equal(appClientSource.includes("pulseTutorialNode({"), false);
  assert.equal(appClientSource.includes("bindProgressObservation({"), false);
  assert.equal(appClientSource.includes("renderTutorialDisabledScopeRowsFn: renderTutorialDisabledScopeRows"), true);
  assert.equal(appClientSource.includes("overlay.innerHTML ="), false);
  assert.equal(appClientSource.includes("disabledScopesPanel.innerHTML ="), false);
  assert.equal(appClientSource.includes("list.innerHTML = rows.map"), false);
  assert.equal(appClientSource.includes("disabledScopesPanel.addEventListener('click', event => {"), false);
  assert.equal(appClientSource.includes("disabledScopesToggle.addEventListener('click', () => {"), false);
  assert.equal(appClientSource.includes("document.getElementById('tutorial-disabled-scopes-close').addEventListener('click', () => {"), false);
  assert.equal(appClientSource.includes("resumeButton.addEventListener('click', async () => {"), false);
  assert.equal(appClientSource.includes("document.getElementById('tutorial-next').addEventListener('click', async () => {"), false);
  assert.equal(appClientSource.includes("document.getElementById('tutorial-back').addEventListener('click', async () => {"), false);
  assert.equal(appClientSource.includes("document.getElementById('tutorial-restart-chapter').addEventListener('click', async () => {"), false);
  assert.equal(appClientSource.includes("document.getElementById('tutorial-disable-page').addEventListener('click', async () => {"), false);
  assert.equal(appClientSource.includes("document.getElementById('tutorial-reset').addEventListener('click', async () => {"), false);
  assert.equal(appClientSource.includes("document.getElementById('tutorial-overlay-handle').addEventListener('pointerdown', event => {"), false);
  assert.equal(appClientSource.includes("window.addEventListener('pointermove', event => {"), false);
  assert.equal(appClientSource.includes("window.addEventListener('pointerup', () => {"), false);
  assert.equal(appClientSource.includes("const advance = async () => {"), false);
  assert.equal(appClientSource.includes("const maybeAdvance = async () => {"), false);
  assert.equal(appClientSource.includes("const requestMaybeAdvance = async () => {"), false);
  assert.equal(appClientSource.includes("const alignProgressToAppPage = async () => {"), false);
  assert.equal(appClientSource.includes("const clearReplayForInteraction = async eventTarget => {"), false);
  assert.equal(appClientSource.includes("document.addEventListener('click', event => {"), false);
  assert.equal(appClientSource.includes("document.addEventListener('submit', event => {"), false);
  assert.equal(appClientSource.includes("setInterval(() => { void requestMaybeAdvance().catch(() => {}); }, 1200);"), false);
  assert.equal(appClientSource.includes("const boot = async () => {"), false);
  assert.equal(appClientSource.includes("const api = async (method, body = null) => {"), false);
  assert.equal(appClientSource.includes("const saveProgress = async next => {"), false);
  assert.equal(appClientSource.includes("const renderDisabledScopes = () => {"), false);
  assert.equal(appClientSource.includes("const publishRuntimeState = () => publishTutorialRuntimeState({"), false);
  assert.equal(appClientSource.includes("let progress = null;"), false);
  assert.equal(appClientSource.includes("let lastRenderedStepId = null;"), false);
  assert.equal(appClientSource.includes("let activeHighlightTarget = null;"), false);
  assert.equal(appClientSource.includes("let activeFocusScope = null;"), false);
  assert.equal(appClientSource.includes("let disabledScopesOpen = false;"), false);
  assert.equal(appClientSource.includes("const currentStep = () => tutorial.steps.find(step => step.id === progress?.stepId) || null;"), false);
  assert.equal(appClientSource.includes("const currentStepIndex = () => stepIndex.get(progress?.stepId || '') ?? -1;"), false);
  assert.equal(appClientSource.includes("const previousStep = () => {"), false);
  assert.equal(appClientSource.includes("const firstStepInChapter = chapterId => tutorial.steps.find(step => step.chapterId === chapterId) || null;"), false);
  assert.equal(appClientSource.includes("const byTarget = target => document.querySelector('[data-tutorial-target=\"' + CSS.escape(target) + '\"]');"), false);
  assert.equal(appClientSource.includes("const clearHighlight = () => {"), false);
  assert.equal(appClientSource.includes("const pulseNode = (node, duration = 1200) =>"), false);
  assert.equal(appClientSource.includes("const flashAutoClick = node => flashTutorialAutoClick({"), false);
  assert.equal(appClientSource.includes("const fillForm = (target, payload) => fillTutorialForm({"), false);
  assert.equal(appClientSource.includes("const focusTutorialTarget = targetName => {"), false);
  assert.equal(appClientSource.includes("const focusTutorialScopeTarget = scopeKey => {"), false);
  assert.equal(appClientSource.includes("const focusScopeFor = target => target?.matches?.('form,section,main') ? target : target?.closest?.('form,section,main') || target || null;"), false);
  assert.equal(appClientSource.includes("const position = target => positionTutorialOverlay({"), false);
  assert.equal(appClientSource.includes("bindTutorialDisabledScopesActions({"), false);
  assert.equal(appClientSource.includes("bindTutorialOverlayDrag({"), false);
  assert.equal(appClientSource.includes("bindTutorialOverlayActions({"), false);
  assert.equal(appClientSource.includes("bindProgressObservation({"), false);
  assert.equal(appClientSource.includes("void boot({ publishRuntimeState });"), false);
  assert.equal(appClientSource.includes("const tutorialScopeCatalog = new Map();"), false);
  assert.equal(appClientSource.includes("const tutorialContextCatalog = new Map();"), false);
  assert.equal(appClientSource.includes("const normalizeProgress = current => {"), false);
  assert.equal(appClientSource.includes("const tutorialSurfaceState = () => {"), false);
  assert.equal(appClientSource.includes("const tutorialDisabledGuidanceRows = current => {"), false);
  assert.equal(appClientSource.includes("const continueTutorialOnPage = async page => {"), false);
  assert.equal(appClientSource.includes("const submitTutorialForm = async target => {"), false);
  assert.equal(appClientSource.includes("const restartCurrentChapter = async () => {"), false);
  assert.equal(appClientSource.includes("const restartFromHere = async () => {"), false);
  assert.equal(appClientSource.includes("const readTodos = async () => fetch('/api/todos')"), false);
  assert.equal(appClientSource.includes("const readNotes = async () => fetch('/api/private-notes')"), false);
  assert.equal(appClientSource.includes("const isComplete = async step => {"), false);
  assert.equal(appClientSource.includes("const renderConceptList = (id, concepts, emptyText) => {"), false);
  assert.equal(appClientSource.includes("node.classList.add('tutorial-auto-click');"), false);
  assert.equal(appClientSource.includes("form.elements.namedItem(key) || form.querySelector('[name=\"' + CSS.escape(key) + '\"]');"), false);
  assert.equal(appClientSource.includes("document.querySelectorAll('[data-tutorial-focus-scope]').forEach(node => node.removeAttribute('data-tutorial-focus-scope'));"), false);
  assert.equal(appClientSource.includes("target.setAttribute('data-tutorial-current', 'true');"), false);
  assert.equal(appClientSource.includes("window.__witnessTutorialApp = {"), false);
  assert.equal(appClientSource.includes("document.getElementById('tutorial-overlay-meta').textContent = step.chapterId.toUpperCase();"), false);
  assert.equal(disabledScopesActionsSource.includes("export async function runTutorialDisabledScopesPanelAction"), true);
  assert.equal(disabledScopesActionsSource.includes("export function bindTutorialDisabledScopesActions"), true);
  assert.equal(disabledScopesActionsSource.includes("export function renderTutorialDisabledScopesActionsFactory"), true);
  assert.equal(clientAdapterSource.includes("export async function tutorialClientApiRequest"), true);
  assert.equal(clientAdapterSource.includes("export async function saveTutorialClientProgress"), true);
  assert.equal(clientAdapterSource.includes("export function createTutorialClientProgressAdapter"), true);
  assert.equal(clientAdapterSource.includes("export function renderTutorialClientDisabledScopes"), true);
  assert.equal(clientAdapterSource.includes("export function renderTutorialClientOverlay"), true);
  assert.equal(clientAdapterSource.includes("export function publishTutorialClientRuntimeSnapshot"), true);
  assert.equal(clientAdapterSource.includes("export function createTutorialClientViewAdapter"), true);
  assert.equal(clientAdapterSource.includes("export function renderTutorialClientAdapterFactory"), true);
  assert.equal(clientAdapterSource.includes("renderTutorialOverlayView({"), true);
  assert.equal(clientAdapterSource.includes("publishTutorialRuntimeState({"), true);
  assert.equal(clientBootstrapSource.includes("export function bindTutorialClientRuntimeAdapters"), true);
  assert.equal(clientBootstrapSource.includes("export function startTutorialClientRuntime"), true);
  assert.equal(clientBootstrapSource.includes("export function renderTutorialClientBootstrapFactory"), true);
  assert.equal(clientBootstrapSource.includes("bindTutorialDisabledScopesActions({"), true);
  assert.equal(clientBootstrapSource.includes("bindTutorialOverlayActions({"), true);
  assert.equal(clientBootstrapSource.includes("bindTutorialOverlayDrag({"), true);
  assert.equal(clientBootstrapSource.includes("bindProgressObservation({"), true);
  assert.equal(clientInteractionsSource.includes("export function createTutorialClientInteractions"), true);
  assert.equal(clientInteractionsSource.includes("export function renderTutorialClientInteractionsFactory"), true);
  assert.equal(clientInteractionsSource.includes("focusTutorialOverlayTargetFn({"), true);
  assert.equal(clientInteractionsSource.includes("focusTutorialOverlayScopeTargetFn({"), true);
  assert.equal(clientInteractionsSource.includes("fillTutorialFormFn({"), true);
  assert.equal(clientInteractionsSource.includes("flashTutorialAutoClickFn({"), true);
  assert.equal(clientInteractionsSource.includes("pulseTutorialNodeFn({"), true);
  assert.equal(clientStateSource.includes("export function createTutorialClientState"), true);
  assert.equal(clientStateSource.includes("export function renderTutorialClientStateFactory"), true);
  assert.equal(disabledScopesViewSource.includes("export function createTutorialDisabledScopeCard"), true);
  assert.equal(disabledScopesViewSource.includes("export function renderTutorialDisabledScopeRows"), true);
  assert.equal(disabledScopesViewSource.includes("export function renderTutorialDisabledScopesViewFactory"), true);
  assert.equal(overlayDomSource.includes("export function createTutorialOverlayDom"), true);
  assert.equal(overlayDomSource.includes("export function renderTutorialOverlayDomFactory"), true);
  assert.equal(overlayInteractionsSource.includes("export function clearTutorialOverlayHighlight"), true);
  assert.equal(overlayInteractionsSource.includes("export function flashTutorialAutoClick"), true);
  assert.equal(overlayInteractionsSource.includes("export function fillTutorialForm"), true);
  assert.equal(overlayInteractionsSource.includes("export function focusTutorialOverlayTarget"), true);
  assert.equal(overlayInteractionsSource.includes("export function renderTutorialOverlayInteractionsFactory"), true);
  assert.equal(overlayViewSource.includes("export function renderTutorialOverlayView"), true);
  assert.equal(overlayViewSource.includes("export function renderTutorialDisabledScopesPanel"), true);
  assert.equal(overlayViewSource.includes("export function publishTutorialRuntimeState"), true);
  assert.equal(overlayViewSource.includes("export function renderTutorialOverlayViewFactory"), true);
  assert.equal(overlayActionsSource.includes("export function bindTutorialOverlayActions"), true);
  assert.equal(overlayActionsSource.includes("export async function runTutorialResumeAction"), true);
  assert.equal(overlayActionsSource.includes("export async function runTutorialResetAction"), true);
  assert.equal(overlayActionsSource.includes("export function renderTutorialOverlayActionsFactory"), true);
  assert.equal(overlayDragSource.includes("export function createTutorialOverlayDragState"), true);
  assert.equal(overlayDragSource.includes("export function setTutorialOverlayPosition"), true);
  assert.equal(overlayDragSource.includes("export function positionTutorialOverlay"), true);
  assert.equal(overlayDragSource.includes("export function bindTutorialOverlayDrag"), true);
  assert.equal(overlayDragSource.includes("export function renderTutorialOverlayDragFactory"), true);
  assert.equal(progressRuntimeSource.includes("export function createTutorialProgressRuntime"), true);
  assert.equal(progressRuntimeSource.includes("export async function advanceTutorialProgress"), true);
  assert.equal(progressRuntimeSource.includes("export async function bootTutorialProgressRuntime"), true);
  assert.equal(progressRuntimeSource.includes("export function bindTutorialProgressObservation"), true);
  assert.equal(progressRuntimeSource.includes("export function renderTutorialProgressRuntimeFactory"), true);
  assert.equal(progressStateSource.includes("export function createTutorialProgressState"), true);
  assert.equal(progressStateSource.includes("export function tutorialStepScope"), true);
  assert.equal(progressStateSource.includes("export function tutorialStepSurfaceContext"), true);
  assert.equal(progressStateSource.includes("export function renderTutorialProgressStateFactory"), true);
  assert.equal(runtimeActionsSource.includes("export function createTutorialRuntimeActions"), true);
  assert.equal(runtimeActionsSource.includes("export async function continueTutorialOnPage"), true);
  assert.equal(runtimeActionsSource.includes("export async function submitTutorialTargetForm"), true);
  assert.equal(runtimeActionsSource.includes("export async function isTutorialStepComplete"), true);
  assert.equal(runtimeActionsSource.includes("export function renderTutorialRuntimeActionsFactory"), true);
  assert.equal(runtimeUiSource.includes("export function appTutorialConfigForSession"), true);
  await assert.rejects(readFile(new URL("../../src/tutorials.js", import.meta.url), "utf8"));
  await assert.rejects(readFile(new URL("../../src/tutorial-runtime-ui.js", import.meta.url), "utf8"));
});
