function freezeStrings(values = []) {
  return Object.freeze(values.map(value => String(value)));
}

export const handlerCatalog = Object.freeze({
  authorableHandlers: freezeStrings([
    "pipeline.platform-config.snapshot",
    "pipeline.platform-config.secret.read",
    "pipeline.platform-config.secret.create",
    "pipeline.platform-config.secret.write",
    "pipeline.platform-config.secret.delete",
    "pipeline.platform-config.datasource.read",
    "pipeline.platform-config.datasource.create",
    "pipeline.platform-config.datasource.update",
    "pipeline.platform-config.datasource.delete",
    "pipeline.platform-config.datasource.test",
    "pipeline.platform-config.access.identity.read",
    "pipeline.platform-config.access.identity.update",
    "pipeline.platform-config.access.feature.read",
    "pipeline.platform-config.access.feature.update",
    "pipeline.platform-config.access.grant.create",
    "pipeline.platform-config.access.grant.revoke",
    "pipeline.platform-config.access.session.assume",
    "pipeline.platform-config.access.session.direct",
    "pipeline.script.run"
  ]),
  pageHandlers: freezeStrings([]),
  dispatchHandlers: freezeStrings([
    "pipeline.platform-config.snapshot",
    "pipeline.platform-config.secret.read",
    "pipeline.platform-config.secret.create",
    "pipeline.platform-config.secret.write",
    "pipeline.platform-config.secret.delete",
    "pipeline.platform-config.datasource.read",
    "pipeline.platform-config.datasource.create",
    "pipeline.platform-config.datasource.update",
    "pipeline.platform-config.datasource.delete",
    "pipeline.platform-config.datasource.test",
    "pipeline.platform-config.access.identity.read",
    "pipeline.platform-config.access.identity.update",
    "pipeline.platform-config.access.feature.read",
    "pipeline.platform-config.access.feature.update",
    "pipeline.platform-config.access.grant.create",
    "pipeline.platform-config.access.grant.revoke",
    "pipeline.platform-config.access.session.assume",
    "pipeline.platform-config.access.session.direct",
    "pipeline.script.run"
  ]),
  handlerMetadata: Object.freeze({
    "pipeline.platform-config.snapshot": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["POST"] }),
    "pipeline.platform-config.secret.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["GET"] }),
    "pipeline.platform-config.secret.create": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["POST"] }),
    "pipeline.platform-config.secret.write": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["PUT"] }),
    "pipeline.platform-config.secret.delete": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["DELETE"] }),
    "pipeline.platform-config.datasource.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["GET"] }),
    "pipeline.platform-config.datasource.create": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["POST"] }),
    "pipeline.platform-config.datasource.update": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["PATCH"] }),
    "pipeline.platform-config.datasource.delete": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["DELETE"] }),
    "pipeline.platform-config.datasource.test": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["POST"] }),
    "pipeline.platform-config.access.identity.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["GET"] }),
    "pipeline.platform-config.access.identity.update": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["PATCH"] }),
    "pipeline.platform-config.access.feature.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["GET"] }),
    "pipeline.platform-config.access.feature.update": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["PATCH"] }),
    "pipeline.platform-config.access.grant.create": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["POST"] }),
    "pipeline.platform-config.access.grant.revoke": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["DELETE"] }),
    "pipeline.platform-config.access.session.assume": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["POST"] }),
    "pipeline.platform-config.access.session.direct": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["POST"] }),
    "pipeline.script.run": Object.freeze({ routeKind: "json", responseKind: "json", methods: ["POST"] })
  })
});
