function freezeStrings(values = []) {
  return Object.freeze(values.map(value => String(value)));
}

export const handlerCatalog = Object.freeze({
  authorableHandlers: freezeStrings([
    "platform.model.read",
    "platform.gaps.read",
    "platform.branch.list",
    "platform.branch.read",
    "platform.branch.create",
    "platform.changeSet.list",
    "platform.changeSet.read",
    "platform.changeSet.create",
    "platform.changeSet.edit",
    "platform.changeSet.removeEdit",
    "platform.changeSet.validate",
    "platform.changeSet.apply",
    "platform.changeSet.reject",
    "platform.changeSet.abandon",
    "platform.testRun.create",
    "platform.testRun.events",
    "platform.testRun.read",
    "platform.proposal.create",
    "platform.proposal.approve",
    "platform.proposal.reject",
    "page.platform"
  ]),
  pageHandlers: freezeStrings(["page.platform"]),
  dispatchHandlers: freezeStrings([
    "platform.model.read",
    "platform.gaps.read",
    "platform.branch.list",
    "platform.branch.read",
    "platform.branch.create",
    "platform.changeSet.list",
    "platform.changeSet.read",
    "platform.changeSet.create",
    "platform.changeSet.edit",
    "platform.changeSet.removeEdit",
    "platform.changeSet.validate",
    "platform.changeSet.apply",
    "platform.changeSet.reject",
    "platform.changeSet.abandon",
    "platform.testRun.create",
    "platform.testRun.events",
    "platform.testRun.read",
    "platform.proposal.create",
    "platform.proposal.approve",
    "platform.proposal.reject",
    "page.platform"
  ]),
  handlerMetadata: Object.freeze({
    "platform.model.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["GET"]) }),
    "platform.gaps.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["GET"]) }),
    "platform.branch.list": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["GET"]) }),
    "platform.branch.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["GET"]) }),
    "platform.branch.create": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.changeSet.list": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["GET"]) }),
    "platform.changeSet.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["GET"]) }),
    "platform.changeSet.create": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.changeSet.edit": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.changeSet.removeEdit": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["DELETE"]) }),
    "platform.changeSet.validate": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.changeSet.apply": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.changeSet.reject": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.changeSet.abandon": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.testRun.create": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.testRun.events": Object.freeze({ routeKind: "stream", responseKind: "stream", methods: Object.freeze(["GET"]) }),
    "platform.testRun.read": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["GET"]) }),
    "platform.proposal.create": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.proposal.approve": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "platform.proposal.reject": Object.freeze({ routeKind: "json", responseKind: "json", methods: Object.freeze(["POST"]) }),
    "page.platform": Object.freeze({ routeKind: "page", responseKind: "page", methods: Object.freeze(["GET"]) })
  })
});
